# 0. Set Up

In [1]:
import tensorflow as tf

In [2]:
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]

In [3]:
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [4]:
# To print from a slicer

def printslc(ds):
    for sales in ds:
        print(sales.numpy())

printslc(tf_dataset)

21
22
-108
31
-1
32
34
31


In [6]:
# Print top 3

printslc(tf_dataset.take(3))

21
22
-108


In [7]:
# Filter only positive

tf_dataset = tf_dataset.filter(lambda x: x>0)
printslc(tf_dataset)

21
22
31
32
34
31


In [8]:
# Transform the data

tf_dataset = tf_dataset.map(lambda y: y*3)
printslc(tf_dataset)

63
66
93
96
102
93


In [9]:
# Shuffle
## From the first n window outputs one randomly then replaces with the rest

tf_dataset = tf_dataset.shuffle(3)
printslc(tf_dataset)

63
66
102
96
93
93


In [10]:
# Batching

tf_dataset = tf_dataset.batch(2)
printslc(tf_dataset)

[66 93]
[63 96]
[102  93]


In [11]:
# Reset
daily_sales_numbers = [21, 22, -108, 31, -1, 32, 34,31]
tf_dataset = tf.data.Dataset.from_tensor_slices(daily_sales_numbers)
tf_dataset

<_TensorSliceDataset element_spec=TensorSpec(shape=(), dtype=tf.int32, name=None)>

In [12]:
# Pipeline
tf_dataset = tf_dataset.filter(lambda x: x>0).map(lambda y: y*3).shuffle(3).batch(2)
printslc(tf_dataset)

[63 96]
[102  93]
[66 93]


# 1. Image processing

In [13]:
images_ds = tf.data.Dataset.list_files('data/images/*/*', shuffle=False)

In [16]:
printslc(images_ds.take(5))

b'data\\images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg'
b'data\\images\\cat\\7 Foods Your Cat Can_t Eat.jpg'
b'data\\images\\cat\\A cat appears to have caught the....jpg'
b'data\\images\\cat\\Adopt-A-Cat Month\xc2\xae - American Humane....jpg'
b'data\\images\\cat\\All About Your Cat_s Tongue.jpg'


In [17]:
len(images_ds)

130

In [18]:
class_name = ['dog', 'cat']

In [29]:
import os
parts = tf.strings.split("data\\images\\dog\\20 Reasons Why Cats Make the Best Pets....jpg", os.path.sep)
parts

<tf.Tensor: shape=(4,), dtype=string, numpy=
array([b'data', b'images', b'dog',
       b'20 Reasons Why Cats Make the Best Pets....jpg'], dtype=object)>

In [22]:
for i in parts:
    print(i)

tf.Tensor(b'images', shape=(), dtype=string)
tf.Tensor(b'dog', shape=(), dtype=string)
tf.Tensor(b'20 Reasons Why Cats Make the Best Pets....jpg', shape=(), dtype=string)


In [165]:
def get_label(file_path):
    import os
    parts = tf.strings.split(file_path, os.path.sep)
    return parts[-2]

                 
get_label("data\\images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg")

<tf.Tensor: shape=(), dtype=string, numpy=b'cat'>

In [32]:
file_path = "data\\images\\cat\\20 Reasons Why Cats Make the Best Pets....jpg"
img = tf.io.read_file(file_path)

print(img)

tf.Tensor(b'\xff\xd8\xff\xe0\x00\x10JFIF\x00\x01\x01\x00\x00\x01\x00\x01\x00\x00\xff\xdb\x00C\x00\x06\x04\x05\x06\x05\x04\x06\x06\x05\x06\x07\x07\x06\x08\n\x10\n\n\t\t\n\x14\x0e\x0f\x0c\x10\x17\x14\x18\x18\x17\x14\x16\x16\x1a\x1d%\x1f\x1a\x1b#\x1c\x16\x16 , #&\')*)\x19\x1f-0-(0%()(\xff\xdb\x00C\x01\x07\x07\x07\n\x08\n\x13\n\n\x13(\x1a\x16\x1a((((((((((((((((((((((((((((((((((((((((((((((((((\xff\xc2\x00\x11\x08\x02\x81\x02\x80\x03\x01"\x00\x02\x11\x01\x03\x11\x01\xff\xc4\x00\x1b\x00\x00\x02\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x03\x04\x01\x02\x05\x00\x06\x07\xff\xc4\x00\x19\x01\x00\x03\x01\x01\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x02\x03\x04\x05\xff\xda\x00\x0c\x03\x01\x00\x02\x10\x03\x10\x00\x00\x01\xf4v\xebu\xf2\xc4\xcc\x87OH\xfazQ\xd3\xd2\x1d\xd3!\x13<\x9fOptE\x13\xaa\xd7M\x00\xc8k#-iN\xa6:Zid\xce\xd2\x8d\x8d\x8b\xd4\x8c\x12\xed\x80\x10Y\xc4\xdc\xac\xbb\x0b\xb48\xee\xa7\x11\xdc:\xd2\xc3\x95=\x17\x95\x16)\x80L\x15\x81\xaf-\xc3I\xc3#\n_\xac\x9fE\x

In [33]:
img = tf.image.decode_jpeg(img)

print(img)

tf.Tensor(
[[[154 185 214]
  [154 185 214]
  [154 185 214]
  ...
  [ 93  87  75]
  [ 92  86  74]
  [ 92  86  74]]

 [[154 185 214]
  [154 185 214]
  [155 186 215]
  ...
  [ 93  87  75]
  [ 92  86  74]
  [ 92  86  74]]

 [[155 186 215]
  [155 186 215]
  [155 186 215]
  ...
  [ 93  87  75]
  [ 92  86  74]
  [ 92  86  74]]

 ...

 [[116  94  97]
  [151 131 133]
  [137 117 118]
  ...
  [ 63  36  43]
  [ 66  39  44]
  [ 70  43  48]]

 [[123 101 103]
  [140 120 119]
  [ 90  71  67]
  ...
  [ 75  43  58]
  [ 81  51  63]
  [ 86  59  68]]

 [[123 105  95]
  [114  96  86]
  [ 76  58  44]
  ...
  [ 96  58  83]
  [ 94  61  80]
  [ 88  57  73]]], shape=(641, 640, 3), dtype=uint8)


In [211]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.resize(img, [128,128])
    img = tf.cast(img, tf.float32)/255.0

    def label_conversion(label):
        label_str = label.numpy().decode('utf-8')
        if label_str == 'cat':
            return 0
        else:
            return 1

    def set_shape_fn(label):
        label = tf.ensure_shape(label, (1))  # Set the shape of the label tensor
        return label

    label = tf.py_function(label_conversion, [label], tf.int32)
    label = tf.py_function(set_shape_fn, [label], tf.int32)  # Set the shape of the tensor

    return img, label

In [212]:
images_ds = images_ds.shuffle(200)

train_size = 104
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

train_ds = train_ds.map(process_image)
test_ds = test_ds.map(process_image)

train_ds = train_ds.batch(64)
test_ds = test_ds.batch(64)


In [100]:
type(train_ds)

tensorflow.python.data.ops.map_op._MapDataset

In [213]:
from tensorflow import keras
from tensorflow.keras import layers
from tensorflow.keras.models import Sequential

data_augmentation = keras.Sequential([
    layers.experimental.preprocessing.RandomFlip('horizontal', input_shape=(128,128,3)),
    layers.experimental.preprocessing.RandomRotation(0.1),
    layers.experimental.preprocessing.RandomZoom(0.1)
])

model = Sequential([
    data_augmentation,
    layers.Conv2D(16,3,padding='same',activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(32,3,padding='same',activation='relu'),
    layers.MaxPooling2D(),
    layers.Conv2D(64,3,padding='same',activation='relu'),
    layers.MaxPooling2D(),

    layers.Flatten(),

    layers.Dense(64, activation='relu'),
    layers.Dense(1, activation='sigmoid') 
])

model.compile(optimizer='adam', 
              loss='binary_crossentropy',
              metrics=['accuracy']
                )


history = model.fit(train_ds, epochs = 5)

Epoch 1/5


ValueError: in user code:

    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\training.py", line 1284, in train_function  *
        return step_function(self, iterator)
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\training.py", line 1268, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\training.py", line 1249, in run_step  **
        outputs = model.train_step(data)
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\training.py", line 1055, in train_step
        return self.compute_metrics(x, y, y_pred, sample_weight)
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\training.py", line 1149, in compute_metrics
        self.compiled_metrics.update_state(y, y_pred, sample_weight)
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 577, in update_state
        self.build(y_pred, y_true)
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 483, in build
        self._metrics = tf.__internal__.nest.map_structure_up_to(
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 631, in _get_metric_objects
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 631, in <listcomp>
        return [self._get_metric_object(m, y_t, y_p) for m in metrics]
    File "c:\Users\jonas\anaconda3\lib\site-packages\keras\engine\compile_utils.py", line 652, in _get_metric_object
        y_t_rank = len(y_t.shape.as_list())

    ValueError: as_list() is not defined on an unknown TensorShape.


In [207]:
train_images, train_labels = next(iter(train_ds))
print("Shape of train_images:", train_images.shape)
print("Shape of train_labels:", train_labels.shape)

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} ValueError: Tensor's shape () is not compatible with supplied shape [1].
Traceback (most recent call last):

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 265, in __call__
    return func(device, token, args)

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 143, in __call__
    outputs = self._call(device, args)

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\ops\script_ops.py", line 150, in _call
    ret = self._func(*args)

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 642, in wrapper
    return func(*args, **kwargs)

  File "C:\Users\jonas\AppData\Local\Temp\__autograph_generated_filejjja7p92.py", line 53, in set_shape_fn
    ag__.converted_call(ag__.ld(tensor).set_shape, ([1],), None, fscope_2)

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 335, in converted_call
    return _call_unconverted(f, args, kwargs, options, False)

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\autograph\impl\api.py", line 459, in _call_unconverted
    return f(*args)

  File "c:\Users\jonas\anaconda3\lib\site-packages\tensorflow\python\framework\ops.py", line 1305, in set_shape
    raise ValueError(f"Tensor's shape {self.shape} is not compatible "

ValueError: Tensor's shape () is not compatible with supplied shape [1].


	 [[{{node EagerPyFunc_1}}]] [Op:IteratorGetNext]

In [189]:
for img, label in train_ds:
    print(label)

InvalidArgumentError: {{function_node __wrapped__IteratorGetNext_output_types_2_device_/job:localhost/replica:0/task:0/device:CPU:0}} Unknown image file format. One of JPEG, PNG, GIF, BMP required.
	 [[{{node DecodeJpeg}}]] [Op:IteratorGetNext]